[package]
name = "twitch_chess"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-ws = "0.3.0"
chrono = "0.4"
colored = "2.2.0"
env_logger = "0.11.6"
futures-util = "0.3.31"
log = "0.4"
tokio = { version="1.42.0", features=["full"] }
